# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'
container: nibedmutha10008/dockerhub:nikita_azure_poc
steps:
- script: python3 --version
  displayName: 'Run a one-line script'

- script: |
    export ScheduleBuildTrigger=true
    sh /home/qiac/bitbucket.sh $ScheduleBuildTrigger
  displayName: 'Run IaC script'
